name: 💡 立项
description: 在Datawhale社区发起一个新的项目
title: "这里写项目名称"
assignees: 
- Sm1les
- finlay-liu
- GYHHAHA
- qiwang067
- zhanhao93
- skywateryang
- andongBlue
- mba1398
body:
- type: markdown
  attributes:
    value: |
      👏欢迎来Datawhale社区发起新的项目，为了便于我们了解你的项目，请填写以下信息~
- type: checkboxes
  attributes:
    label: "你是否已经阅读并同意《Datawhale社区贡献协议》？"
    options:
    - label: "我已阅读并同意[《Datawhale社区贡献协议》](https://github.com/datawhalechina/DOPMC/blob/main/CONTRIBUTING.md)"
      required: true
- type: textarea
  id: description
  attributes:
    label: "项目简介"
    description: "请对你的项目做个简单的介绍~"
    render: markdown
  validations:
    required: true
- type: textarea
  id: motivation
  attributes:
    label: "立项理由"
    description: "请描述一下你发起这个项目的理由~"
    render: markdown
  validations:
    required: true
- type: textarea
  id: audience
  attributes:
    label: "项目受众"
    description: "请描述一下这个项目所面向的受众~"
    render: markdown
  validations:
    required: true
- type: textarea
  id: highlight
  attributes:
    label: "项目亮点"
    description: "请描述一下你的项目亮点是什么？如果已有类似项目的话，那与其相比你的项目亮点又有哪些？"
    render: markdown
  validations:
    required: true
- type: textarea
  id: plan
  attributes:
    label: "项目规划"
    placeholder: "请分别从内容、时间和人员三个方面描述一下你的项目规划~"
    render: markdown
  validations:
    required: true
- type: textarea
  id: profile
  attributes:
    label: "项目负责人"
    description: "请在下方填写项目负责人的GitHub主页链接~"
    render: markdown
  validations:
    required: false
- type: checkboxes
  attributes:
    label: "备注：发起立项申请后DOPMC将会在24小时之内给出答复，如超时未答复请添加DOPMC负责人微信（微信号：at-Sm1les）问询~"
    options:
    - label: "我已知悉上述备注"
      required: true
